### ISSUE TITLE
Rust idiomatic wrapper

### ISSUE THREAD

**Issue by fabricedesre** [richardanaya/webidl-loader#1]
This is more a question than an issue: are there plans to also include an idiomatic Rust wrapper to not have to use so unsafe blocks?
Also, what's the "failure" value for the returned handles?

**Comment by richardanaya** [comment]
Good question @fabricedesre , I have no plans to write a rust wrapper library, to be honest, most apps I've written on this tech only needed a few exposed functions.  I usually just stick all the unsafe wrapper functions in a single file and forget about them. That said ... there's probably some better way to wrap things like callbacks and I could see someone writing a wrapper for just like canvas 2d or webgl eventually ... but ... I dunno i'f i'd make it official.  Especially since this project is supposed to be technology agnostic!

As you might imagine, I have a lot of work in just making the generation of the generated webidl functions working perfectly!

Can you tell me what you mean by "failure" values with an example? Thank you

**Comment by fabricedesre** [comment]
> Can you tell me what you mean by "failure" values with an example?

Let's say you call `Window_get_document` with a parameter that is not a valid window handle. What happens?

**Comment by richardanaya** [comment]
Good question! Right now I don’t have a mechanism, but I think returning -1
would be best since functions generally return pointers to things in memory
and there’s no negative position in memory. Maybe I could also offer an
option for you to have a function called if it exists as an error handler.

**Comment by fabricedesre** [comment]
Yep, returning -1 seems good.
